### ISSUE TITLE
Problems compiling for Mac

### ISSUE THREAD

**Issue by gingerbeardman** [Tuxality/maketmd#3]
Sorry but I don't do much command line compiling.

I have openssl installed using `brew` at `/usr/local/opt/openssl/`

```
$ make
g++  -c maketmd.cpp -o maketmd.o
maketmd.cpp:37:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [maketmd.o] Error 1
```

I added `CFLAGS = "-I/usr/local/opt/openssl/include"` the following to the Makefile

```
$ make
g++ "-I/usr/local/opt/openssl/include" -c maketmd.cpp -o maketmd.o
maketmd.cpp:44:10: fatal error: 'byteswap.h' file not found
#include <byteswap.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [maketmd.o] Error 1
```

at this point I fear I'm heading down a rabbit hole, as `glibc` has not been ported to macOS

any help appreciated!

**Comment by Tuxality** [comment]
Sorry for late reply. I've merged fixes proposed by **mondul**, which should allow you to compile this project and create proper TMDs. While I don't have macOS based device anymore (died alongside with all my data), it should work. If you have any issues please let me know.

**Comment by gingerbeardman** [comment]
It now compiles, cheers!
